# Generated by Django 4.0.5 on 2022-06-23 07:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Huawei', 'Huawei'), ('Nokia', 'Nokia'), ('Sony', 'Sony'), ('LG', 'LG'), ('HTC', 'HTC'), ('Motorola', 'Motorola'), ('Lenovo', 'Lenovo'), ('Xiaomi', 'Xiaomi'), ('Google', 'Google'), ('Honor', 'Honor'), ('Oppo', 'Oppo'), ('Realme', 'Realme'), ('OnePlus', 'OnePlus'), ('vivo', 'vivo'), ('Meizu', 'Meizu'), ('BlackBerry', 'BlackBerry'), ('Asus', 'Asus'), ('Alcatel', 'Alcatel'), ('ZTE', 'ZTE'), ('Microsoft', 'Microsoft'), ('Vodafone', 'Vodafone'), ('Energizer', 'Energizer'), ('Cat', 'Cat'), ('Sharp', 'Sharp'), ('Micromax', 'Micromax'), ('Infinix', 'Infinix'), ('TCL', 'TCL'), ('Ulefone', 'Ulefone'), ('Tecno', 'Tecno'), ('BLU', 'BLU'), ('Blackview', 'Blackview'), ('Acer', 'Acer'), ('Panasonic', 'Panasonic'), ('Plum', 'Plum')], default='Samsung', max_length=50, verbose_name='Mobile Brand')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('weight', models.CharField(max_length=20, verbose_name='Net Wight')),
                ('dimensions', models.CharField(max_length=100, verbose_name='Dimensions')),
                ('body_material', models.CharField(max_length=100, verbose_name='Body Material')),
                ('sim', models.CharField(max_length=100, verbose_name='Sim')),
                ('screen_size', models.CharField(max_length=100, verbose_name='Screen Size')),
                ('resolution', models.CharField(max_length=100, verbose_name='Resolution')),
                ('os', models.CharField(max_length=100, verbose_name='Operating System')),
                ('chipset', models.CharField(max_length=100, verbose_name='Chipset')),
                ('processor', models.CharField(max_length=100, verbose_name='Processor')),
                ('front_camera', models.CharField(max_length=100, verbose_name='Front Camera')),
                ('front_camera_video_recording', models.CharField(max_length=100, verbose_name='Front Camera Video Recording')),
                ('back_camera', models.CharField(max_length=100, verbose_name='Back Camera')),
                ('back_camera_video_recording', models.CharField(max_length=100, verbose_name='Back Camera Video Recording')),
                ('usb_type', models.CharField(max_length=100, verbose_name='USB Type')),
                ('otg', models.BooleanField(verbose_name='OTG')),
                ('fingerprint', models.BooleanField(verbose_name='Fingerprint')),
                ('face_lock', models.BooleanField(verbose_name='Face Lock')),
                ('made_in', models.CharField(max_length=50, verbose_name='Made in')),
                ('battery_capacity', models.CharField(max_length=100, verbose_name='Battery Capacity')),
                ('water_resistance', models.BooleanField(verbose_name='Water Resistance')),
                ('bluetooth', models.BooleanField(verbose_name='Bluetooth')),
                ('fast_charging', models.CharField(max_length=100, verbose_name='Fast Charging')),
                ('sensors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('radio', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('gps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('wlan', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('network', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
            ],
        ),
    ]
