# Generated by Django 4.0.5 on 2022-06-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('mobile_description', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mobile.mobile_description', verbose_name='Select Mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Ram_Rom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('ram', models.CharField(max_length=100, verbose_name='RAM')),
                ('rom', models.CharField(max_length=100, verbose_name='ROM')),
                ('mobile_description', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mobile.mobile_description', verbose_name='Select Mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Image')),
                ('mobile_colors', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mobile.mobile_colors', verbose_name='Select Mobile')),
            ],
        ),
    ]
