# Generated by Django 4.0.5 on 2022-06-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_mobile_colors_mobile_ram_rom_mobile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_images',
            name='photo',
            field=models.ImageField(upload_to='product\\mobile\\images', verbose_name='Image'),
        ),
    ]
